export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const UPDATE_PROFILE_PHOTO_REQUEST = "UPDATE_PROFILE_PHOTO_REQUEST";
export const UPDATE_PROFILE_PHOTO_SUCCESS = "UPDATE_PROFILE_PHOTO_SUCCESS";
export const UPDATE_PROFILE_PHOTO_FAIL = "UPDATE_PROFILE_PHOTO_FAIL";

export const UPDATE_COMPANY_LOGO_REQUEST = "UPDATE_COMPANY_LOGO_REQUEST";
export const UPDATE_COMPANY_LOGO_SUCCESS = "UPDATE_COMPANY_LOGO_SUCCESS";
export const UPDATE_COMPANY_LOGO_FAIL = "UPDATE_COMPANY_LOGO_FAIL";

export const HOST_GET_REQUEST = "HOST_GET_REQUEST";
export const HOST_GET_SUCCESS = "HOST_GET_SUCCESS";
export const HOST_GET_FAIL = "HOST_GET_FAIL";

export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";

export const INTERVIEW_LIST_REQUEST = "INTERVIEW_LIST_REQUEST";
export const INTERVIEW_LIST_SUCCESS = "INTERVIEW_LIST_SUCCESS";
export const INTERVIEW_LIST_FAIL = "INTERVIEW_LIST_FAIL";

export const USER_INTERVIEW_LIST_SUCCESS = "USER_INTERVIEW_LIST_SUCCESS";
export const USER_INTERVIEW_LIST_REQUEST = "USER_INTERVIEW_LIST_REQUEST";
export const USER_INTERVIEW_LIST_FAIL = "USER_INTERVIEW_LIST_FAIL";

export const INTERVIEW_GET_REQUEST = "INTERVIEW_GET_REQUEST";
export const INTERVIEW_GET_SUCCESS = "INTERVIEW_GET_SUCCESS";
export const INTERVIEW_GET_FAIL = "INTERVIEW_GET_FAIL";

export const HAS_USER_APPLIED_REQUEST = "HAS_USER_APPLIED_REQUEST";
export const HAS_USER_APPLIED_SUCCESS = "HAS_USER_APPLIED_SUCCESS";
export const HAS_USER_APPLIED_FAIL = "HAS_USER_APPLIED_FAIL";

export const INTERVIEW_CREATE_REQUEST = "INTERVIEW_CREATE_REQUEST";
export const INTERVIEW_CREATE_SUCCESS = "INTERVIEW_CREATE_SUCCESS";
export const INTERVIEW_CREATE_FAIL = "INTERVIEW_CREATE_FAIL";

export const ADD_TO_QUEUE_REQUEST = "ADD_TO_QUEUE_REQUEST";
export const ADD_TO_QUEUE_SUCCESS = "ADD_TO_QUEUE_SUCCESS";
export const ADD_TO_QUEUE_FAIL = "ADD_TO_QUEUE_FAIL";

export const REMOVE_FROM_QUEUE_REQUEST = "REMOVE_FROM_QUEUE_REQUEST";
export const REMOVE_FROM_QUEUE_SUCCESS = "REMOVE_FROM_QUEUE_SUCCESS";
export const REMOVE_FROM_QUEUE_FAIL = "REMOVE_FROM_QUEUE_FAIL";

export const GET_ALL_USERS_THAT_APPLIED_SUCCESS = "GET_ALL_USERS_THAT_APPLIED_SUCCESS";
export const GET_ALL_USERS_THAT_APPLIED_REQUEST = "GET_ALL_USERS_THAT_APPLIED_REQUEST";
export const GET_ALL_USERS_THAT_APPLIED_FAIL = "GET_ALL_USERS_THAT_APPLIED_FAIL";

export const GET_JOBS_APPLIED_TO_SUCCESS = "GET_JOBS_APPLIED_TO_SUCCESS";
export const GET_JOBS_APPLIED_TO_REQUEST = "GET_JOBS_APPLIED_TO_REQUEST";
export const GET_JOBS_APPLIED_TO_FAIL = "GET_JOBS_APPLIED_TO_FAIL";

export const GET_QUEUE_REQUEST = "GET_QUEUE_REQUEST";
export const GET_QUEUE_SUCCESS = "GET_QUEUE_SUCCESS";
export const GET_QUEUE_FAIL = "GET_QUEUE_FAIL";

export const ADD_TO_FAV_REQUEST = "ADD_TO_FAV_REQUEST";
export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";
export const ADD_TO_FAV_FAIL = "ADD_TO_FAV_FAIL";

export const ADD_TO_WORKEXP_REQUEST = "ADD_TO_WORKEXP_REQUEST";
export const ADD_TO_WORKEXP_SUCCESS = "ADD_TO_WORKEXP_SUCCESS";
export const ADD_TO_WORKEXP_FAIL = "ADD_TO_WORKEXP_FAIL";

export const DELETE_WORKEXP_REQUEST = "DELETE_WORKEXP_REQUEST";
export const DELETE_WORKEXP_SUCCESS = "DELETE_WORKEXP_SUCCESS";
export const DELETE_WORKEXP_FAIL = "DELETE_WORKEXP_FAIL";

export const DELETE_EDU_REQUEST = "DELETE_EDU_REQUEST";
export const DELETE_EDU_SUCCESS = "DELETE_EDU_SUCCESS";
export const DELETE_EDU_FAIL = "DELETE_EDU_FAIL";

export const ADD_TO_EDU_REQUEST = "ADD_TO_EDU_REQUEST";
export const ADD_TO_EDU_SUCCESS = "ADD_TO_EDU_SUCCESS";
export const ADD_TO_EDU_FAIL = "ADD_TO_EDU_FAIL";


export const USER_FAVS_LIST_SUCCESS = "USER_FAVS_LIST_SUCCESS";
export const USER_FAVS_LIST_REQUEST = "USER_FAVS_LIST_REQUEST";
export const USER_FAVS_LIST_FAIL = "USER_FAVS_LIST_FAIL";

export const USER_WORKEXP_LIST_SUCCESS = "USER_WORKEXP_LIST_SUCCESS";
export const USER_WORKEXP_LIST_REQUEST = "USER_WORKEXP_LIST_REQUEST";
export const USER_WORKEXP_LIST_FAIL = "USER_WORKEXP_LIST_FAIL";

export const USER_EDU_LIST_SUCCESS = "USER_EDU_LIST_SUCCESS";
export const USER_EDU_LIST_REQUEST = "USER_EDU_LIST_REQUEST";
export const USER_EDU_LIST_FAIL = "USER_EDU_LIST_FAIL";


export const ADD_TO_APPLICATIONS_REQUEST = "ADD_TO_APPLICATIONS_REQUEST";
export const ADD_TO_APPLICATIONS_SUCCESS = "ADD_TO_APPLICATIONS_SUCCESS";
export const ADD_TO_APPLICATIONS_FAIL = "ADD_TO_APPLICATIONS_FAIL";

export const GET_APPLICATIONS_REQUEST = "GET_APPLICATIONS_REQUEST";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_FAIL = "GET_APPLICATIONS_FAIL";

export const GET_MYJOBS_REQUEST = "GET_MYJOBS_REQUEST";
export const GET_MYJOBS_SUCCESS = "GET_MYJOBS_SUCCESS";
export const GET_MYJOBS_FAIL = "GET_MYJOBS_FAIL";

export const GET_ISUSERPROFILEUPDATE_REQUEST = "GET_ISUSERPROFILEUPDATE_REQUEST";
export const GET_ISUSERPROFILEUPDATE_SUCCESS = "GET_ISUSERPROFILEUPDATE_SUCCESS";
export const GET_ISUSERPROFILEUPDATE_FAIL = "GET_ISUSERPROFILEUPDATE_FAIL";

export const UPDATE_USER_CV_REQUEST = "UPDATE_USER_CV_REQUEST";
export const UPDATE_USER_CV_SUCCESS = "UPDATE_USER_CV_SUCCESS";
export const UPDATE_USER_CV_FAIL = "UPDATE_USER_CV_FAIL";